--------------------------------------------------------
--  File created - Thứ Tư-tháng 10-30-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTENDANCES
--------------------------------------------------------

  CREATE TABLE "QLST"."ATTENDANCES" 
   (	"ATTENDANCEID" VARCHAR2(30 BYTE), 
	"STAFFID" VARCHAR2(30 BYTE), 
	"SHIFT" NVARCHAR2(30), 
	"SHIFTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAFF_TS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "QLST"."CATEGORIES" 
   (	"CATEGORYID" VARCHAR2(30 BYTE), 
	"CATEGORYTITLE" NVARCHAR2(50), 
	"DESCRIPTION" NVARCHAR2(500)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCT_TS" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "QLST"."CLIENTS" 
   (	"CLIENTID" VARCHAR2(30 BYTE), 
	"CLIENTNAME" NVARCHAR2(50), 
	"PHONENUMBER" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ADDRESS" NVARCHAR2(300), 
	"CLIENTTYPE" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIENT_TS" ;
--------------------------------------------------------
--  DDL for Table INVOICEDETAILS
--------------------------------------------------------

  CREATE TABLE "QLST"."INVOICEDETAILS" 
   (	"QUANTITY" NUMBER(*,0), 
	"LINETOTAL" NUMBER, 
	"DISCOUNT" NUMBER(*,0), 
	"INVOICEID" VARCHAR2(30 BYTE), 
	"PRODUCTID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INVOICE_TS" ;
--------------------------------------------------------
--  DDL for Table INVOICES
--------------------------------------------------------

  CREATE TABLE "QLST"."INVOICES" 
   (	"INVOICEID" VARCHAR2(30 BYTE), 
	"CREATEDATE" DATE, 
	"TOTALAMOUNT" NUMBER, 
	"STAFFID" VARCHAR2(30 BYTE), 
	"CLIENTID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INVOICE_TS" ;
--------------------------------------------------------
--  DDL for Table JOBS
--------------------------------------------------------

  CREATE TABLE "QLST"."JOBS" 
   (	"JOBID" VARCHAR2(30 BYTE), 
	"JOBNAME" NVARCHAR2(100), 
	"SHIFTSALARY" NUMBER, 
	"DESCRIPTION" NVARCHAR2(200)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAFF_TS" ;
--------------------------------------------------------
--  DDL for Table PRICEHISTORIES
--------------------------------------------------------

  CREATE TABLE "QLST"."PRICEHISTORIES" 
   (	"PRICEID" VARCHAR2(30 BYTE), 
	"SELLINGPRICE" NUMBER, 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"PRODUCTID" VARCHAR2(30 BYTE), 
	"PURCHASEPRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCT_TS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "QLST"."PRODUCTS" 
   (	"PRODUCTID" VARCHAR2(30 BYTE), 
	"PRODUCTNAME" NVARCHAR2(100), 
	"DESCRIPTION" NVARCHAR2(1000), 
	"STOCKQUANTITY" NUMBER(*,0), 
	"CATEGORYID" VARCHAR2(30 BYTE), 
	"SUPPLIERID" VARCHAR2(30 BYTE), 
	"PRODUCTIONDATE" DATE, 
	"EXPIRATIONDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCT_TS" ;
--------------------------------------------------------
--  DDL for Table PURCHASEORDERDETAILS
--------------------------------------------------------

  CREATE TABLE "QLST"."PURCHASEORDERDETAILS" 
   (	"QUANTITY" NUMBER(*,0), 
	"LINETOTAL" NUMBER, 
	"PURCHASEORDERID" VARCHAR2(30 BYTE), 
	"PRODUCTID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INVOICE_TS" ;
--------------------------------------------------------
--  DDL for Table PURCHASEORDERS
--------------------------------------------------------

  CREATE TABLE "QLST"."PURCHASEORDERS" 
   (	"PURCHASEORDERID" VARCHAR2(30 BYTE), 
	"CREATEDATE" DATE, 
	"TOTALAMOUNT" NUMBER, 
	"SUPPLIERID" VARCHAR2(30 BYTE), 
	"STAFFID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INVOICE_TS" ;
--------------------------------------------------------
--  DDL for Table SALARYHISTORIES
--------------------------------------------------------

  CREATE TABLE "QLST"."SALARYHISTORIES" 
   (	"SALARYID" VARCHAR2(30 BYTE), 
	"SALARY" NUMBER, 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"STAFFID" VARCHAR2(30 BYTE), 
	"JOBID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAFF_TS" ;
--------------------------------------------------------
--  DDL for Table STAFFS
--------------------------------------------------------

  CREATE TABLE "QLST"."STAFFS" 
   (	"STAFFID" VARCHAR2(30 BYTE), 
	"STAFFNAME" NVARCHAR2(50), 
	"DATEOFBIRTH" DATE, 
	"PHONENUMBER" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"ADDRESS" NVARCHAR2(300), 
	"SALARYINCREMENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAFF_TS" ;
--------------------------------------------------------
--  DDL for Table SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "QLST"."SUPPLIERS" 
   (	"SUPPLIERID" VARCHAR2(30 BYTE), 
	"SUPPLIERNAME" NVARCHAR2(100), 
	"PHONENUMBER" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ADDRESS" NVARCHAR2(300), 
	"NOTE" NVARCHAR2(1000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUPPLIER_TS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "QLST"."USERS" 
   (	"USERID" VARCHAR2(30 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"ROLE" NVARCHAR2(50), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"LASTLOGIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAFF_TS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "QLST"."CLIENTS" MODIFY ("CLIENTID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."CLIENTS" MODIFY ("CLIENTNAME" NOT NULL ENABLE);
  ALTER TABLE "QLST"."CLIENTS" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "QLST"."CLIENTS" ADD PRIMARY KEY ("CLIENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIENT_TS"  ENABLE;
  ALTER TABLE "QLST"."CLIENTS" MODIFY ("CLIENTTYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICEDETAILS
--------------------------------------------------------

  ALTER TABLE "QLST"."INVOICEDETAILS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "QLST"."INVOICEDETAILS" MODIFY ("LINETOTAL" NOT NULL ENABLE);
  ALTER TABLE "QLST"."INVOICEDETAILS" MODIFY ("INVOICEID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."INVOICEDETAILS" MODIFY ("PRODUCTID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."INVOICEDETAILS" ADD PRIMARY KEY ("INVOICEID", "PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INVOICE_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVOICES
--------------------------------------------------------

  ALTER TABLE "QLST"."INVOICES" MODIFY ("INVOICEID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."INVOICES" MODIFY ("CREATEDATE" NOT NULL ENABLE);
  ALTER TABLE "QLST"."INVOICES" MODIFY ("TOTALAMOUNT" NOT NULL ENABLE);
  ALTER TABLE "QLST"."INVOICES" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."INVOICES" MODIFY ("CLIENTID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."INVOICES" ADD PRIMARY KEY ("INVOICEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INVOICE_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "QLST"."PRODUCTS" MODIFY ("PRODUCTID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PRODUCTS" MODIFY ("PRODUCTNAME" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PRODUCTS" MODIFY ("STOCKQUANTITY" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PRODUCTS" ADD PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCT_TS"  ENABLE;
  ALTER TABLE "QLST"."PRODUCTS" MODIFY ("CATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PRODUCTS" MODIFY ("SUPPLIERID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PRODUCTS" MODIFY ("PRODUCTIONDATE" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PRODUCTS" MODIFY ("EXPIRATIONDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PURCHASEORDERDETAILS
--------------------------------------------------------

  ALTER TABLE "QLST"."PURCHASEORDERDETAILS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PURCHASEORDERDETAILS" MODIFY ("LINETOTAL" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PURCHASEORDERDETAILS" MODIFY ("PURCHASEORDERID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PURCHASEORDERDETAILS" MODIFY ("PRODUCTID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PURCHASEORDERDETAILS" ADD PRIMARY KEY ("PURCHASEORDERID", "PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INVOICE_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFFS
--------------------------------------------------------

  ALTER TABLE "QLST"."STAFFS" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."STAFFS" MODIFY ("STAFFNAME" NOT NULL ENABLE);
  ALTER TABLE "QLST"."STAFFS" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "QLST"."STAFFS" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "QLST"."STAFFS" ADD PRIMARY KEY ("STAFFID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAFF_TS"  ENABLE;
  ALTER TABLE "QLST"."STAFFS" MODIFY ("ADDRESS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOBS
--------------------------------------------------------

  ALTER TABLE "QLST"."JOBS" MODIFY ("JOBID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."JOBS" MODIFY ("JOBNAME" NOT NULL ENABLE);
  ALTER TABLE "QLST"."JOBS" MODIFY ("SHIFTSALARY" NOT NULL ENABLE);
  ALTER TABLE "QLST"."JOBS" ADD PRIMARY KEY ("JOBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAFF_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "QLST"."SUPPLIERS" MODIFY ("SUPPLIERID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."SUPPLIERS" MODIFY ("SUPPLIERNAME" NOT NULL ENABLE);
  ALTER TABLE "QLST"."SUPPLIERS" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "QLST"."SUPPLIERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "QLST"."SUPPLIERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "QLST"."SUPPLIERS" ADD PRIMARY KEY ("SUPPLIERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SUPPLIER_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PURCHASEORDERS
--------------------------------------------------------

  ALTER TABLE "QLST"."PURCHASEORDERS" MODIFY ("PURCHASEORDERID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PURCHASEORDERS" MODIFY ("CREATEDATE" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PURCHASEORDERS" MODIFY ("TOTALAMOUNT" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PURCHASEORDERS" MODIFY ("SUPPLIERID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PURCHASEORDERS" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PURCHASEORDERS" ADD PRIMARY KEY ("PURCHASEORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INVOICE_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALARYHISTORIES
--------------------------------------------------------

  ALTER TABLE "QLST"."SALARYHISTORIES" ADD PRIMARY KEY ("SALARYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "QLST"."SALARYHISTORIES" MODIFY ("SALARYID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."SALARYHISTORIES" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "QLST"."SALARYHISTORIES" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "QLST"."SALARYHISTORIES" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."SALARYHISTORIES" MODIFY ("JOBID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTENDANCES
--------------------------------------------------------

  ALTER TABLE "QLST"."ATTENDANCES" MODIFY ("ATTENDANCEID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."ATTENDANCES" MODIFY ("STAFFID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."ATTENDANCES" ADD PRIMARY KEY ("ATTENDANCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAFF_TS"  ENABLE;
  ALTER TABLE "QLST"."ATTENDANCES" MODIFY ("SHIFT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRICEHISTORIES
--------------------------------------------------------

  ALTER TABLE "QLST"."PRICEHISTORIES" ADD PRIMARY KEY ("PRICEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "QLST"."PRICEHISTORIES" MODIFY ("PRICEID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PRICEHISTORIES" MODIFY ("SELLINGPRICE" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PRICEHISTORIES" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PRICEHISTORIES" MODIFY ("PRODUCTID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."PRICEHISTORIES" MODIFY ("PURCHASEPRICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "QLST"."USERS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "QLST"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "QLST"."USERS" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "QLST"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "QLST"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STAFF_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "QLST"."CATEGORIES" MODIFY ("CATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "QLST"."CATEGORIES" MODIFY ("CATEGORYTITLE" NOT NULL ENABLE);
  ALTER TABLE "QLST"."CATEGORIES" ADD PRIMARY KEY ("CATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PRODUCT_TS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTENDANCES
--------------------------------------------------------

  ALTER TABLE "QLST"."ATTENDANCES" ADD CONSTRAINT "FK_ATTENDANCE_STAFF" FOREIGN KEY ("STAFFID")
	  REFERENCES "QLST"."STAFFS" ("STAFFID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICEDETAILS
--------------------------------------------------------

  ALTER TABLE "QLST"."INVOICEDETAILS" ADD CONSTRAINT "FK_INVOICEDETAIL_INVOICE" FOREIGN KEY ("INVOICEID")
	  REFERENCES "QLST"."INVOICES" ("INVOICEID") ENABLE;
  ALTER TABLE "QLST"."INVOICEDETAILS" ADD CONSTRAINT "FK_INVOICEDETAIL_PRODUCT" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "QLST"."PRODUCTS" ("PRODUCTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICES
--------------------------------------------------------

  ALTER TABLE "QLST"."INVOICES" ADD CONSTRAINT "FK_INVOICE_CLIENT" FOREIGN KEY ("CLIENTID")
	  REFERENCES "QLST"."CLIENTS" ("CLIENTID") ENABLE;
  ALTER TABLE "QLST"."INVOICES" ADD CONSTRAINT "FK_INVOICE_STAFF" FOREIGN KEY ("STAFFID")
	  REFERENCES "QLST"."STAFFS" ("STAFFID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRICEHISTORIES
--------------------------------------------------------

  ALTER TABLE "QLST"."PRICEHISTORIES" ADD CONSTRAINT "FK_PRICEHISTORY_PRODUCT" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "QLST"."PRODUCTS" ("PRODUCTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "QLST"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCT_CATEGORY" FOREIGN KEY ("CATEGORYID")
	  REFERENCES "QLST"."CATEGORIES" ("CATEGORYID") ENABLE;
  ALTER TABLE "QLST"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCT_SUPPLIER" FOREIGN KEY ("SUPPLIERID")
	  REFERENCES "QLST"."SUPPLIERS" ("SUPPLIERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURCHASEORDERDETAILS
--------------------------------------------------------

  ALTER TABLE "QLST"."PURCHASEORDERDETAILS" ADD CONSTRAINT "FK_PURCHASEORDERDETAIL_PURCHASEORDER" FOREIGN KEY ("PURCHASEORDERID")
	  REFERENCES "QLST"."PURCHASEORDERS" ("PURCHASEORDERID") ENABLE;
  ALTER TABLE "QLST"."PURCHASEORDERDETAILS" ADD CONSTRAINT "FK_PURCHASEORDERDETAIL_PRODUCT" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "QLST"."PRODUCTS" ("PRODUCTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURCHASEORDERS
--------------------------------------------------------

  ALTER TABLE "QLST"."PURCHASEORDERS" ADD CONSTRAINT "FK_PURCHASEORDER_SUPPLIER" FOREIGN KEY ("SUPPLIERID")
	  REFERENCES "QLST"."SUPPLIERS" ("SUPPLIERID") ENABLE;
  ALTER TABLE "QLST"."PURCHASEORDERS" ADD CONSTRAINT "FK_PURCHASEORDER_STAFF" FOREIGN KEY ("STAFFID")
	  REFERENCES "QLST"."STAFFS" ("STAFFID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALARYHISTORIES
--------------------------------------------------------

  ALTER TABLE "QLST"."SALARYHISTORIES" ADD CONSTRAINT "FK_SALARYHISTORY_STAFF" FOREIGN KEY ("STAFFID")
	  REFERENCES "QLST"."STAFFS" ("STAFFID") ENABLE;
  ALTER TABLE "QLST"."SALARYHISTORIES" ADD CONSTRAINT "FK_SALARYHISTORY_JOB" FOREIGN KEY ("JOBID")
	  REFERENCES "QLST"."JOBS" ("JOBID") ENABLE;
